version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
      time: '01:00'
    open-pull-requests-limit: 10
    reviewers:
      - jsone-studios
    ignore:
      - dependency-name: 'mockwebserver'
        versions: ['4.x']
