name: Publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # We want all history so we can get all commits since previous git tag
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ossrh
          server-username: OSSRH_USERNAME # env variable for username in deploy
          server-password: OSSRH_PASSWORD # env variable for password in deploy
          gpg-private-key: ${{ secrets.OSSRH_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: OSSRH_GPG_PASSPHRASE # env variable for GPG private key passphrase
      - name: Cache .m2 repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Deploy to Maven Central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          OSSRH_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
        run: ./mvnw -B deploy -Pdeploy
      - name: Create release notes
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          previousTag=$(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 --max-count=1))
          currentTag=$(git describe --tags --abbrev=0)
          echo "Creating release notes for $previousTag...$currentTag"
          echo "# What's Changed" > release-notes.md
          git log "$previousTag...$currentTag" --format="- %s ([%h](https://github.com/sonallux/spotify-web-api/commit/%H))" >> release-notes.md
          cat release-notes.md
      - name: Create release on GitHub
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: release-notes.md
          files: |
            spotify-web-api-core/src/main/resources/spotify-web-api.yml
            spotify-web-api-generator-open-api/spotify-web-api-openapi.yml
